
services:
  db:
    image: postgres:latest
    container_name: encounter-builder-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: encounterBuilder
    volumes:
      - pgdata:/var/lib/postgresql/data
      #- ./postgres-config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: encounter-builder-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/pgadmin_data
    depends_on:
      - db

volumes:
  pgdata:
  pgadmin_data: