services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - /mnt/c/Users/cburt/dynamodb-data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -dbPath /home/dynamodblocal/data"
    working_dir: /home/dynamodblocal