// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package writeMonsters

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AttackDamageBlock struct {
	ID         int32
	AttackID   pgtype.Int4
	DamageRoll pgtype.Text
	DamageType pgtype.Text
}

type FocusSpellCasting struct {
	ID             int32
	MonsterID      pgtype.Int4
	Dc             pgtype.Int4
	Mod            pgtype.Text
	Tradition      pgtype.Text
	SpellcastingID pgtype.Text
	Name           pgtype.Text
	Description    pgtype.Text
	CastLevel      pgtype.Text
}

type FocusSpellCastingSpell struct {
	ID                  int32
	FocusSpellCastingID pgtype.Int4
	SpellID             pgtype.Text
}

type InnateSpellCasting struct {
	ID             int32
	MonsterID      pgtype.Int4
	Dc             pgtype.Int4
	Tradition      pgtype.Text
	Mod            pgtype.Text
	SpellcastingID pgtype.Text
	Description    pgtype.Text
	Name           pgtype.Text
}

type InnateSpellUse struct {
	ID                   int32
	InnateSpellCastingID pgtype.Int4
	SpellID              pgtype.Text
	Level                pgtype.Int4
	Uses                 pgtype.Text
}

type Item struct {
	ID          string
	MonsterID   pgtype.Int4
	Name        pgtype.Text
	Category    pgtype.Text
	Description pgtype.Text
	Level       pgtype.Text
	Type        pgtype.Text
	Rarity      pgtype.Text
	Size        pgtype.Text
	Range       pgtype.Text
	Reload      pgtype.Text
	Bulk        pgtype.Text
	Quantity    pgtype.Text
	PricePer    pgtype.Int4
	PriceCp     pgtype.Int4
	PriceSp     pgtype.Int4
	PriceGp     pgtype.Int4
	PricePp     pgtype.Int4
}

type ItemTrait struct {
	ID     int32
	ItemID pgtype.Text
	Trait  pgtype.Text
}

type Monster struct {
	ID               int32
	Name             string
	Level            pgtype.Text
	FocusPoints      pgtype.Int4
	TraitsRarity     pgtype.Text
	TraitsSize       pgtype.Text
	AttrStr          pgtype.Text
	AttrDex          pgtype.Text
	AttrCon          pgtype.Text
	AttrWis          pgtype.Text
	AttrInt          pgtype.Text
	AttrCha          pgtype.Text
	SavesFort        pgtype.Text
	SavesFortDetail  pgtype.Text
	SavesRef         pgtype.Text
	SavesRefDetail   pgtype.Text
	SavesWill        pgtype.Text
	SavesWillDetail  pgtype.Text
	SavesException   pgtype.Text
	AcValue          pgtype.Text
	AcDetail         pgtype.Text
	HpDetail         pgtype.Text
	HpValue          pgtype.Int4
	PerceptionMod    pgtype.Text
	PerceptionDetail pgtype.Text
}

type MonsterAction struct {
	ID         int32
	MonsterID  pgtype.Int4
	ActionType pgtype.Text
	Name       pgtype.Text
	Text       pgtype.Text
	Actions    pgtype.Text
	Category   pgtype.Text
	Rarity     pgtype.Text
	Dc         pgtype.Text
}

type MonsterActionTrait struct {
	ID              int32
	MonsterActionID pgtype.Int4
	Trait           pgtype.Text
}

type MonsterAttack struct {
	ID                  int32
	MonsterID           pgtype.Int4
	AttackCategory      pgtype.Text
	Name                pgtype.Text
	AttackType          pgtype.Text
	ToHitBonus          pgtype.Text
	EffectsCustomString pgtype.Text
	EffectsValues       []string
}

type MonsterDamageModifier struct {
	ID               int32
	MonsterID        pgtype.Int4
	ModifierCategory pgtype.Text
	Value            pgtype.Int4
	DamageType       pgtype.Text
}

type MonsterImmunity struct {
	ID        int32
	MonsterID pgtype.Int4
	Immunity  pgtype.Text
}

type MonsterLanguage struct {
	ID        int32
	MonsterID pgtype.Int4
	Language  pgtype.Text
}

type MonsterModifierDouble struct {
	ID          int32
	ModifierID  pgtype.Int4
	DoubleValue pgtype.Text
}

type MonsterModifierException struct {
	ID         int32
	ModifierID pgtype.Int4
	Exception  pgtype.Text
}

type MonsterMovement struct {
	ID           int32
	MonsterID    pgtype.Int4
	MovementType pgtype.Text
	Speed        pgtype.Text
	Notes        pgtype.Text
}

type MonsterSense struct {
	ID        int32
	MonsterID pgtype.Int4
	Name      pgtype.Text
	Range     pgtype.Text
	Acuity    pgtype.Text
	Detail    pgtype.Text
}

type MonsterSkill struct {
	ID        int32
	MonsterID pgtype.Int4
	Name      pgtype.Text
	Value     pgtype.Int4
}

type MonsterSkillSpecial struct {
	ID         int32
	SkillID    pgtype.Int4
	Value      pgtype.Int4
	Label      pgtype.Text
	Predicates []string
}

type MonsterTrait struct {
	ID        int32
	MonsterID pgtype.Int4
	Trait     pgtype.Text
}

type PreparedSlot struct {
	ID                     int32
	PreparedSpellCastingID pgtype.Int4
	Level                  pgtype.Text
	SpellID                pgtype.Text
}

type PreparedSpellCasting struct {
	ID             int32
	MonsterID      pgtype.Int4
	Dc             pgtype.Int4
	Tradition      pgtype.Text
	Mod            pgtype.Text
	SpellcastingID pgtype.Text
	Description    pgtype.Text
}

type RitualDatum struct {
	ID               int32
	SpellID          pgtype.Text
	PrimaryCheck     pgtype.Text
	SecondaryCasters pgtype.Text
	SecondaryCheck   pgtype.Text
}

type Spell struct {
	ID                          string
	Name                        pgtype.Text
	CastLevel                   pgtype.Text
	SpellBaseLevel              pgtype.Text
	Description                 pgtype.Text
	Range                       pgtype.Text
	CastTime                    pgtype.Text
	CastRequirements            pgtype.Text
	Rarity                      pgtype.Text
	AtWill                      pgtype.Bool
	SpellCastingBlockLocationID pgtype.Text
	Uses                        pgtype.Text
	Ritual                      pgtype.Bool
	Targets                     pgtype.Text
}

type SpellArea struct {
	ID       int32
	SpellID  pgtype.Text
	AreaType pgtype.Text
	Value    pgtype.Text
	Detail   pgtype.Text
}

type SpellDefense struct {
	ID      int32
	SpellID pgtype.Text
	Save    pgtype.Text
	Basic   pgtype.Bool
}

type SpellDuration struct {
	ID        int32
	SpellID   pgtype.Text
	Sustained pgtype.Bool
	Duration  pgtype.Text
}

type SpellTrait struct {
	ID      int32
	SpellID pgtype.Text
	Trait   pgtype.Text
}

type SpontaneousSlot struct {
	ID                        int32
	SpontaneousSpellCastingID pgtype.Int4
	Level                     pgtype.Text
	Casts                     pgtype.Text
}

type SpontaneousSpellCasting struct {
	ID        int32
	MonsterID pgtype.Int4
	Dc        pgtype.Int4
	IDString  pgtype.Text
	Tradition pgtype.Text
	Mod       pgtype.Text
}

type SpontaneousSpellList struct {
	ID                        int32
	SpontaneousSpellCastingID pgtype.Int4
	SpellID                   pgtype.Text
}
